### ISSUE TITLE
Rename content directories to better match our agenda or session names?

### ISSUE THREAD

**Issue by gonuke** [UW-Madison-ACI/boot-camps#25]
I am thinking we should make the directories in our repo better map onto the session names/concepts so that learners can find their way around.

Thoughts?

**Comment by gidden** [comment]
I know that the testing directory is nested in the python directory. This
decision appears to have been made for a previous bootcamp when they were
all wrapped together (indeed, the testing is in python). I think it could
be moved out without loss of continuity, though.

Matthew Gidden
Nuclear Energy University Programs Fellow
The University of Wisconsin -- Madison
Ph. 225.892.3192
Fax 608.263.7451

**Comment by katyhuff** [comment]
That's a fine idea, and I think you should rearrange it however it seems easiest. 
But, just for historical accuracy, I thought I'd add that the reasoning was actually because of a very long discussion on a software carpentry list ("gits") where it was decided that, since we might want to teach, say, data_structures and flow_control and unit_testing, etc. in other languages, we should keep things in the organization such that language is the top level and concepts were the lower levels.

**Comment by gonuke** [comment]
Aaah... and following my chat with Travis King... this would make it harder to merge it back into SWC.  Probably better to recreate this effect in the agenda and breadcrumbs.

**Comment by lmichael107** [comment]
We've since resolved this issue.
